project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs

website:
  title: "Joshua Simmons"
  google-analytics: "G-03KZZS8MH5"
  navbar:
    left:
      - icon: github
        href: https://github.com/simmonsja/
      - icon: twitter
        href: https://bsky.app/profile/jasimm.bsky.social
format:
  html:
    theme: flatly
    css: styles.css
    mainfont: Montserrat
    monofont: Fira Code



